var footer = '';

footer +=	'<div id="footer">'
footer +=	'	<div class="wrap">'
footer +=	'		<img src="../common/images/comm/footer_logo.gif" alt="선명안 한의안과학회 하단 로고" />'
footer +=	'		<ul class="footermenu">'
footer +=	'			<li><a href="#" class="first"><img src="../common/images/comm/footer_menu1.gif" alt="이용약관" /></a></li>'
footer +=	'			<li><a href="#"><img src="../common/images/comm/footer_menu2.gif" alt="개인정보보호정책" /></a></li>'
footer +=	'			<li><a href="#"><img src="../common/images/comm/footer_menu3.gif" alt="이메일수집거부" /></a></li>'
footer +=	'			<li><a href="#"><img src="../common/images/comm/footer_menu4.gif" alt="사이트맵" /></a></li>'
footer +=	'		</ul>'
footer +=	'		<div class="family">'
footer +=	'			<select id="selFamilySite" onchange="fnFamilySiteLink();">'
footer +=	'				<option value="">학회 정회원 한의원</option>'
footer +=	'                <option value="#">한의원2</option>'
footer +=	'                <option value="#">한의원3</option>'
footer +=	'                <option value="#">한의원4</option>'
footer +=	'                <option value="#">한의원5</option>'
footer +=	'			</select>'
footer +=	'		</div>'
footer +=	'		<p class="address"><img src="../common/images/comm/address.gif" alt="주소:서울시 성북구 석관동 4-2번지 두산아파트 상가 4층, 전화:02-968-7007, 팩스:02-967-2165 사업자등록번호 : 209-96-10734, 대표:황 재 옥, 이메일:jaeokkorea@hanmail.net   COPYRIGHT(C)2013 선명안한의안과학회 ALL RIGHT RESERVED." /></p>'
footer +=	'	</div>'
footer +=	'</div>'
footer +=	'<script language="javascript">'
footer +=	'    function fnFamilySiteLink() {'
footer +=	'        if ($("#selFamilySite").val() != "") {'
footer +=	'            window.open($("#selFamilySite").val());'
footer +=	'        }'
footer +=	'    }'
footer +=	'</script>'

document.write(footer);