var header = '';

header +=	'<div id="header">'
header +=	'	<div class="wrap">'
header +=	'		<div class="logo">'
header +=	'			<h1><a href="#"><img src="../common/images/comm/logo.png" alt="선명안 한의안과학회 로고"></a></h1>'
header +=	'		</div>'
header +=	'		<div class="topmenu">'
header +=	'			<ul>'
header +=	'				<li class="first"><a href="#"><img src="../common/images/comm/topmenu01.png" alt="처음으로" /></a></li>'
header +=	'				<li><a href="#"><img src="../common/images/comm/topmenu02.png" alt="로그인" /></a></li>'
header +=	'				<li><a href="#"><img src="../common/images/comm/topmenu03.png" alt="회원가입" /></a></li>'
header +=	'				<li><a href="#"><img src="../common/images/comm/topmenu04.png" alt="마이페이지" /></a></li>'
header +=	'				<li><a href="#"><img src="../common/images/comm/topmenu05.png" alt="사이트맵" /></a></li>'
header +=	'				<li><a href="#" class="intranet"><img src="../common/images/comm/topmenu06.png" alt="인트라넷" /></a></li>'
header +=	'			</ul>'
header +=	'		</div>'
header +=	'		<div class="nav">'
header +=	'			<ul>'
header +=	'				<li><a href="#"><img src="../common/images/comm/menu01.png" alt="학회소개" /></a></li>'
header +=	'				<li><a href="#"><img src="../common/images/comm/menu02.png" alt="전문진료" /></a></li>'
header +=	'				<li><a href="#"><img src="../common/images/comm/menu03.png" alt="치료방법" /></a></li>'
header +=	'				<li><a href="#"><img src="../common/images/comm/menu04.png" alt="치료성공사례" /></a></li>'
header +=	'				<li><a href="#"><img src="../common/images/comm/menu05.png" alt="상담/예약" /></a></li>'
header +=	'				<li><a href="#"><img src="../common/images/comm/menu06.png" alt="소통/공유" /></a></li>'
header +=	'				<li id="viewtotal"><a href="#"><span>전체보기+</span></a></li>'
header +=	'			</ul>'
header +=	'		</div>'
header +=	'		<div class="social">'
header +=	'			<ul>'
header +=	'				<li><a href="#"><img src="../common/images/comm/ico_twitter.png" alt="트위터 바로가기" /></a></li>'
header +=	'				<li><a href="#"><img src="../common/images/comm/ico_facebook.png" alt="페이스북 바로가기" /></a></li>'
header +=	'				<li><a href="#"><img src="../common/images/comm/ico_blog.png" alt="블로그 바로가기" /></a></li>'
header +=	'				<li><a href="#"><img src="../common/images/comm/ico_youtube.png" alt="유투브 바로가기" /></a></li>'
header +=	'			</ul>'
header +=	'		</div>'
header +=	'	</div>'
header +=	'	<div class="total">'
header +=	'		<div class="wrap">'
header +=	'			<ul>'
header +=	'				<li class="submenu1"><span class="hide">학회소개</span>'
header +=	'					<ul>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb01_1.gif" alt="인사말" /></a></li>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb01_2.gif" alt="학회소개" /></a></li>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb01_3.gif" alt="학회 네트워크" /></a></li>'
header +=	'					</ul>'
header +=	'				</li>'
header +=	'				<li class="submenu2"><span class="hide">전문진료</span>'
header +=	'					<ul>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb02_1.gif" alt="노안" /></a></li>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb02_2.gif" alt="시력저하증" /></a></li>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb02_3.gif" alt="시력강화" /></a></li>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb02_4.gif" alt="백내장" /></a></li>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb02_5.gif" alt="녹내장" /></a></li>'
header +=	'					</ul>'
header +=	'				</li>'
header +=	'				<li class="submenu3"><span class="hide">치료방법</span>'
header +=	'					<ul>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb03_1.gif" alt="한약치료" /></a></li>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb03_2.gif" alt="약침요법" /></a></li>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb03_3.gif" alt="침,뜸,부항" /></a></li>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb03_4.gif" alt="보사요법" /></a></li>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb03_5.gif" alt="자석요법" /></a></li>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb03_6.gif" alt="테이핑요법" /></a></li>'
header +=	'					</ul>'
header +=	'				</li>'
header +=	'				<li class="submenu4"><span class="hide">치료성공사례</span>'
header +=	'					<ul>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb04_1.gif" alt="논문,저서" /></a></li>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb04_2.gif" alt="치료후기" /></a></li>'
header +=	'					</ul>'
header +=	'				</li>'
header +=	'				<li class="submenu5"><span class="hide">상담/예약</span>'
header +=	'					<ul>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb05_1.gif" alt="진료상담" /></a></li>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb05_2.gif" alt="온라인예약" /></a></li>'
header +=	'					</ul>'
header +=	'				</li>'
header +=	'				<li class="submenu6"><span class="hide">소통/공유</span>'
header +=	'					<ul>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb06_1.gif" alt="공지사항" /></a></li>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb06_2.gif" alt="FAQ" /></a></li>'
header +=	'						<li><a href="#"><img src="../common/images/comm/gnb06_3.gif" alt="상담 및 문의" /></a></li>'
header +=	'					</ul>'
header +=	'				</li>'
header +=	'			</ul>'
header +=	'		</div>'
header +=	'	</div>'
header +=	'</div>'

document.write(header);

